name: Continuous Deployment Serverless

on:
  workflow_call:
    inputs:
      PROD_INSTANCES:
        description: 'The instances where to deploy the code on prod.
                      Needs to be a stringified JSON array.
                      Example: "["prod", "dev-hes"]"'
        required: true
        type: string

jobs:
  createMatrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::${{ toJson(inputs.PROD_INSTANCES) }}"

  deployProd:
    runs-on: ubuntu-latest
    needs: [ createMatrix ]

    strategy:
      matrix:
        instance: ${{ fromJSON(needs.createMatrix.outputs.matrix) }}

    steps:
      - name: deploy ${{ matrix.instance }}
        run: |
          echo "Deploying to ${{ matrix.instance }}"
          export SERVERLESS_ACCESS_KEY=${{ secrets.SERVERLESS_TOKEN }}
          mv .npmrc_config .npmrc
          npm ci
          npx cloud promote dev ${{ matrix.instance }}