name: Continuous Deployment bit.dev

on:
  workflow_call:
    secrets:
      BIT_TOKEN:
        description: 'The token used to access your bit.dev environment.
          Managed by Doppler'
        required: true

jobs:
  deployDev:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '--skip-ci') && github.event_name == 'push' && github.ref_name != 'main'"

    steps:
      - name: Checkout source code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Bit Version Manager
        run: npm i -g @teambit/bvm
      - name: Install latest Bit version
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${{ secrets.BIT_TOKEN }}

      # - name: Install packages using bit
      #   run: |
      #     bit install
      #     bit add orc/apis/* orc/constants/* orc/design-tokens/* orc/functions/* orc/services/* orc/test-data/* orc/ui/foundations/* orc/ui/compositions/* orc/* hes/apis/* hes/apps/* hes/bar/* hes/functions/* hes/hooks/* hes/test-data/* hes/ui/compositions/* hes/*
      #     bit compile
      #     bit link --rewire

      - name: Set correct branch
        id: lane_name
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            BRANCH_NAME=${{ github.head_ref }}
          else
            BRANCH_NAME=${{ github.ref_name }}
          fi
          BRANCH_NAME="${BRANCH_NAME##*/}"
          BRANCH_NAME="${BRANCH_NAME,,}"
          echo "::set-output name=branch_name::$BRANCH_NAME"
        shell: bash

      - name: Create or use existing lane for pending components
        run: |
          bit import --skip-dependency-installation
          bit lane switch dechea.orc/${{ steps.lane_name.outputs.branch_name }} --get-all --skip-dependency-installation || bit lane create ${{ steps.lane_name.outputs.branch_name }}
          bit install 
          bit add orc/apis/* orc/constants/* orc/design-tokens/* orc/functions/* orc/hooks/* orc/services/* orc/services/auth/* orc/test-data/* orc/ui/foundations/* orc/ui/compositions/* orc/* hes/apis/* hes/apps/* hes/bar/* hes/functions/* hes/hooks/* hes/test-data/* hes/ui/compositions/* hes/ui/foundations/* hes/*
          bit compile
          bit link --rewire
          bit snap -m "${{ github.event.head_commit.message }}"
          bit export

      - name: Test pending components
        run: |
          bit test
          bit lane switch main

      - name: Commit changes made to .bitmap
        uses: EndBug/add-and-commit@v9
        with:
          add: .bitmap
          author_name: ${{ github.actor }}
          message: 'update .bitmap with new component versions (automated). [--skip-ci]'

  deployProd:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && github.base_ref == 'main'

    steps:
      - name: Checkout source code
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4

      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Bit Version Manager
        run: npm i -g @teambit/bvm
      - name: Install latest Bit version
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${{ secrets.BIT_TOKEN }}

      # - name: Install packages using bit
      #   run: |
      #     bit install --skip-import
      #     bit add orc/apis/* orc/constants/* orc/design-tokens/* orc/functions/* orc/services/* orc/test-data/* orc/ui/foundations/* orc/ui/compositions/* orc/* hes/apis/* hes/apps/* hes/bar/* hes/functions/* hes/hooks/* hes/test-data/* hes/ui/compositions/* hes/*
      #     bit compile
      #     bit link --rewire

      - name: Set correct branch
        id: lane_name
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            BRANCH_NAME=${{ github.head_ref }}
          else
            BRANCH_NAME=${{ github.ref_name }}
          fi
          BRANCH_NAME="${BRANCH_NAME##*/}"
          BRANCH_NAME="${BRANCH_NAME,,}"
          echo "::set-output name=branch_name::$BRANCH_NAME"
        shell: bash

      - name: Hard-tag pending components
        run: |
          bit import --skip-dependency-installation
          bit lane switch dechea.orc/${{ steps.lane_name.outputs.branch_name }} --get-all --skip-dependency-installation
          bit install
          bit add orc/apis/* orc/constants/* orc/design-tokens/* orc/functions/* orc/hooks/* orc/services/* orc/services/auth/* orc/test-data/* orc/ui/foundations/* orc/ui/compositions/* orc/* hes/apis/* hes/apps/* hes/bar/* hes/functions/* hes/hooks/* hes/test-data/* hes/ui/compositions/* hes/ui/foundations/* hes/*
          bit compile
          bit link --rewire
          bit lane switch main --skip-dependency-installation
          bit lane merge ${{ steps.lane_name.outputs.branch_name }}
          bit tag --ignore-issues "CircularDependencies" --snapped
          bit export

      - name: Commit changes made to .bitmap
        uses: EndBug/add-and-commit@v9
        with:
          add: .bitmap
          author_name: ${{ github.actor }}
          message: 'update .bitmap with new component versions (automated).'
