name: Continuous Deployment Fauna

on:
  workflow_call:
    inputs:
      FAUNA_DATABASE:
        required: true
        type: string
      MUTATION_TEST:
        required: false
        type: boolean
    secrets:
      GITHUB_PAT:
        required: true
      FAUNA_REGION:
        required: true
      FAUNA_TOKEN:
        required: true
      SONAR_TOKEN_SCHEMA:
        required: true

jobs:
  set-correct-envs:
    runs-on: ubuntu-latest

    outputs:
      BRANCH_NAME: ${{ steps.set_branch.outputs.BRANCH_NAME }}

    steps:
      - name: Logging
        run: |
          echo
        shell: bash

      - name: Set correct branch
        id: set_branch
        run: |
          if [[ ${{ github.event_name }} == 'pull_request' ]]; then
            echo "::set-output name=BRANCH_NAME::$GITHUB_HEAD_REF"
            echo "PULL REQUEST!"
          else
            echo "::set-output name=BRANCH_NAME::$GITHUB_REF_NAME"
            echo "SOMETHING ELSE!"
          fi
        shell: bash

  build:
    runs-on: ubuntu-latest

    needs: set-correct-envs

    steps:
      - uses: actions/checkout@v3
      - name: Fauna Domain IaC
        uses: Dechea/Fauna-Domain-IaC_-Action-@main
        with:
          GITHUB_REPOSITORIES: ${{ inputs.GITHUB_REPOSITORIES}}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          FAUNA_DATABASE: ${{ inputs.FAUNA_DATABASE}}
          FAUNA_REGION: ${{ secrets.FAUNA_REGION }}
          FAUNA_TOKEN: ${{ secrets.FAUNA_TOKEN }}
          MUTATION_TEST: ${{ inputs.MUTATION_TEST }}

      - uses: actions/download-artifact@v3
        name: Get coverage report artifact
        with:
          name: coverage-files
          path: coverage

      - uses: sonarsource/sonarcloud-github-action@master
        name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SCHEMA }}
          GITHUB_TOKEN: ${{ github.token }}

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@master
        # Force to fail step after specific time
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SCHEMA }}
