name: Continuous Deployment bit.dev

on:
  workflow_call:
    inputs:
      COMPONENTS_DIRECTORIES:
        description: 'The directories which contains the components.
                      Eg. /orc/apis/* orc/components/*'
        required: true
        type: string
      SCOPE_NAME:
        description: 'The name of the scope.
                      Eg. dechea.orc, dechea.hes'
        required: true
        type: string
      ENVIRONMENT:
        description: 'The environment where to you want to run this script.
                      Eg. Prod, Dev'
        required: true
        type: string
    secrets:
      BIT_TOKEN:
        description: 'The token used to access your bit.dev environment.
                      Managed by Doppler'
        required: true

jobs:
  tag-and-export:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Bit Version Manager
        run: npm i -g @teambit/bvm
      - name: Install latest Bit version
        run: bvm install
      - name: add bvm bin folder to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Set up bit config
        run: |
          bit config set analytics_reporting false
          bit config set anonymous_reporting false
          bit config set user.token ${{ secrets.BIT_TOKEN }}

      - name: Install packages using bit
        run: |
          bit install

      - name: Create or use existing lane for pending components
        if: "contains(inputs.ENVIRONMENT, 'Dev')"
        run: |
          bit switch ${GITHUB_REF##*/} || bit lane create ${GITHUB_REF##*/}
          bit snap ${{ inputs.COMPONENTS_DIRECTORIES }} -m "add new feature"
          bit export

      - name: Test pending components
        if: "contains(inputs.ENVIRONMENT, 'Dev')"
        run: bit test -s ${{ inputs.SCOPE_NAME }}

      - name: Hard-tag pending components
        if: "contains(inputs.ENVIRONMENT, 'Prod')"
        run: |
          bit lane merge ${GITHUB_REF##*/}

      - name: Commit changes made to .bitmap
        uses: EndBug/add-and-commit@v9
        with:
          add: .bitmap
          author_name: ${{ github.actor }}
          message: "update .bitmap with new component versions (automated). --skip-ci"