name: Continuous Deployment Fauna

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORIES:
        required: true
        type: string
      FAUNA_DATABASE:
        required: true
        type: string
      MUTATION_TEST:
        required: false
        type: boolean
    secrets:
      GITHUB_PAT:
        required: true
#      GITHUB_TOKEN:
#        required: true
      FAUNA_REGION:
        required: true
      FAUNA_TOKEN:
        required: true
      SONAR_TOKEN_SCHEMA:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Fauna Domain IaC
        uses: Dechea/Fauna-Domain-IaC_-Action-@feature/test-if-condition
        with:
          GITHUB_REPOSITORIES: ${{ inputs.GITHUB_REPOSITORIES}}
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
          FAUNA_DATABASE: ${{ inputs.FAUNA_DATABASE}}
          FAUNA_REGION: ${{ secrets.FAUNA_REGION }}
          FAUNA_TOKEN: ${{ secrets.FAUNA_TOKEN }}
          MUTATION_TEST: ${{ inputs.MUTATION_TEST }}

      - uses: actions/download-artifact@v3
        name: Get coverage report artifact
        with:
          name: coverage-files
          path: coverage

      - uses: sonarsource/sonarcloud-github-action@master
        name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_SCHEMA }}
          GITHUB_TOKEN: ${{ github.token }}
